# Generated by Django 4.2 on 2023-06-22 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Loyiha nomi')),
                ('date', models.DateField(verbose_name='Vaqt')),
                ('client', models.CharField(max_length=200, verbose_name='Klient ismi')),
                ('demo_url', models.URLField(blank=True, max_length=100, null=True, verbose_name='Demo sayt manzili')),
                ('github_url', models.URLField(blank=True, max_length=100, null=True, verbose_name='Githubdagi manzili')),
                ('direction', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('telegram_bot', 'Telegram bot')], max_length=12, verbose_name="Loyiha yo'nalishi")),
                ('short_description', models.TextField(verbose_name="Qisqa ma'lumot")),
                ('full_description', models.TextField(verbose_name="To'liq ma'lumot")),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project_image/', verbose_name='Project')),
                ('create_at', models.DateTimeField(max_length=200)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
    ]
