# Generated by Django 4.2 on 2023-06-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
