# Generated by Django 4.2 on 2023-06-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_image_create_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Holati'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='project_image/', verbose_name='Image'),
        ),
    ]
