# Generated by Django 4.2 on 2023-07-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_image_status_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sequence_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tartib raqami'),
        ),
        migrations.AlterField(
            model_name='project',
            name='direction',
            field=models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('full_stack', 'Full Stack'), ('telegram_bot', 'Telegram bot')], max_length=12, verbose_name="Loyiha yo'nalishi"),
        ),
    ]
