# Generated by Django 4.2 on 2023-12-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_comment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='Short desription')),
                ('link', models.URLField(verbose_name='Link')),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='qr_images/', verbose_name='image of QR kod')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Added time')),
            ],
        ),
    ]
