# Generated by Django 4.2 on 2023-12-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_mylink'),
    ]

    operations = [
        migrations.AddField(
            model_name='mylink',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='Is Private'),
        ),
    ]
